/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.List;

import org.example.enums.SplitType;
import org.example.model.User;
import org.example.repository.InMemoryGroupRepository;
import org.example.service.BalanceSheetService;
import org.example.service.DebtSimplificationService;
import org.example.service.ExpenseService;
import org.example.service.GroupService;

public class App {
    public static void main(String[] args) {
         User shubh = new User("u1", "Shubh");
        User bob   = new User("u2", "Bob");
        User tom   = new User("u3", "Tom");
        User jake  = new User("u4", "Jake");


        InMemoryGroupRepository repo  = new InMemoryGroupRepository();
        BalanceSheetService balanceSheetService = new BalanceSheetService();
        ExpenseService expenseService = new ExpenseService(balanceSheetService);
        DebtSimplificationService simplificationService = new DebtSimplificationService();

        GroupService groupService = new GroupService(repo, expenseService, simplificationService);

        String goaTripId = groupService.createGroup("Goa Trip", List.of(shubh,bob,tom));
        String missGroup = groupService.createGroup("Non-Group expense", List.of(shubh,bob,tom,jake));

              /* ---------- add expenses ---------- */
       /* ---------- add expenses ---------- */
        groupService.addExpense(goaTripId,
                "Lunch Day-1", 100, shubh,
                List.of(shubh, bob), SplitType.EQUAL, null);

        groupService.addExpense(goaTripId,
                "Lunch Day-2", 100, bob,
                List.of(bob, tom), SplitType.EQUAL, null);

        /* ---------- simplify & print ---------- */
        groupService.simplifyDebts(goaTripId);
        groupService.printBalances(goaTripId);
    }
}

