/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.time.LocalDateTime;
import java.time.temporal.ChronoUnit;

import org.example.enums.PricingStrategyType;
import org.example.enums.VehicleType;
import org.example.factory.PricingStrategyFactory;
import org.example.factory.VehicleFactory;
import org.example.model.EntryGate;
import org.example.model.ExitGate;
import org.example.model.ParkingFloor;
import org.example.model.ParkingSpot;
import org.example.model.Vehicle;
import org.example.service.ParkingLot;
import org.example.utils.DateTimeParser;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }
public static void main(String[] args) {
        ParkingLot lot = ParkingLot.getInstance();
        EntryGate entryGate = new EntryGate("EG1");
        ExitGate exitGate = new ExitGate("XG1");

        lot.setPricingStrategy(PricingStrategyFactory.get(PricingStrategyType.valueOf("EVENT_BASED")));

        ParkingFloor floor1 = new ParkingFloor("Floor1");
        floor1.addSpot(new ParkingSpot("F1S1", VehicleType.BIKE));
        floor1.addSpot(new ParkingSpot("F1S2", VehicleType.CAR));
        floor1.addSpot(new ParkingSpot("F1S3", VehicleType.TRUCK));
        floor1.addSpot(new ParkingSpot("F1S4", VehicleType.CAR));
        lot.addFloor(floor1);

        System.out.println("--------------------------");

        Vehicle bike1 = VehicleFactory.create("KA01AB1234", VehicleType.BIKE);
        Vehicle bike2 = VehicleFactory.create("KA01AB5678", VehicleType.BIKE);
        LocalDateTime entryTime = DateTimeParser.parse("21 May 7:30 AM 2025");
        System.out.println(entryTime.truncatedTo(ChronoUnit.HOURS));

        Thread t1 = new Thread(() -> lot.parkVehicle(bike1, entryTime));
        Thread t2 = new Thread(() -> lot.parkVehicle(bike2, entryTime));

        t1.start();
        t2.start();

}

}
