/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.time.LocalDateTime;

import org.example.enums.VehicleType;
import org.example.factory.VehicleFactory;
import org.example.model.Branch;
import org.example.model.User;
import org.example.repository.BookingRepository;
import org.example.repository.BranchRepository;
import org.example.service.BookingService;
import org.example.strategy.booking.LeastBookedVehicle;
import org.example.strategy.payment.CreditCardPaymentStrategy;
import org.example.strategy.payment.WalletPaymentStrategy;
import org.example.strategy.pricing.HourlyPricingStrategy;
import org.example.utils.DateTimeParser;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
         BranchRepository branchRepo = new BranchRepository();
        BookingRepository bookingRepo = new BookingRepository();

        Branch branch1 = new Branch("B1","Delhi");
        Branch branch2 = new Branch("B2","Jaipur");
            branchRepo.addBranch(branch1);
        branchRepo.addBranch(branch2);
         branch1.addVehicle(VehicleFactory.create(VehicleType.SEDAN, "DEL1234", 25, 3.5));
        branch1.addVehicle(VehicleFactory.create(VehicleType.SEDAN, "DEL5678", 22, 3));
        branch1.addVehicle(VehicleFactory.create(VehicleType.SUV, "DELB100", 30, 4));

        branch2.addVehicle(VehicleFactory.create(VehicleType.SEDAN, "RJ1234", 25, 4));

         User user = new User("U1", "John Doe", "john@example.com");
        LocalDateTime start = DateTimeParser.parse("21 May 7:30 AM 2026");
        LocalDateTime end = DateTimeParser.parse("21 May 12:30 PM 2026");
        BookingService bookingService = BookingService.getInstance(
                branchRepo,
                bookingRepo,
                new LeastBookedVehicle(),
                new HourlyPricingStrategy()
        );

               System.out.println("--------------");
               Thread T1 = new Thread(()->{
                System.out.println(Thread.currentThread().getName() + " started!");
            bookingService.bookVehicle(
                    "B1",
                    VehicleType.SUV,
                    start,
                    end,
                    user,
                    new CreditCardPaymentStrategy(),
                    branch1,
                    branch2,
                    100.0
            );
            System.out.println(Thread.currentThread().getName() + " ended!");
               });
               Thread T2 = new Thread(()->{
                  System.out.println(Thread.currentThread().getName() + " started!");
            bookingService.bookVehicle(
                    "B1",
                    VehicleType.SUV,
                    start,
                    end,
                    user,
                    new WalletPaymentStrategy(),
                    branch1,
                    branch2,
                    100.0
            );
            System.out.println(Thread.currentThread().getName() + " ended!");
               });

           
        T1.start();
        T2.start();

        System.out.println("--------------");    
            
    }
}
