/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example.app;

import org.example.list.LinkedList;

import main.java.org.example.app.CORPattern.LogHandler;
import main.java.org.example.app.CORPattern.ConcreteStrategies.DebugLogger;
import main.java.org.example.app.CORPattern.ConcreteStrategies.ErrorLogger;
import main.java.org.example.app.LogAppenderStrategies.LogAppender;
import main.java.org.example.app.LogAppenderStrategies.ConcreteLogAppenders.ConsoleAppender;
import main.java.org.example.app.LogAppenderStrategies.ConcreteLogAppenders.FileAppender;
import main.java.org.example.app.enums.Loglevel;

import static org.example.utilities.StringUtils.join;
import static org.example.utilities.StringUtils.split;
import static org.example.app.MessageUtils.getMessage;

import org.apache.commons.text.WordUtils;

public class App {

    private static LogHandler getChainOfLogger(LogAppender appender)
    {
        LogHandler errorLogger = new ErrorLogger(Loglevel.ERROR, appender);
        LogHandler debugLogger = new DebugLogger(Loglevel.DEBUG, appender);
        LogHandler infoLogger = new DebugLogger(Loglevel.INFO, appender);
        infoLogger.setNextLogger(debugLogger);
        debugLogger.setNextLogger(errorLogger);
        return infoLogger;
    }
    public static void main(String[] args) {
        LogAppender consoleAppender = new ConsoleAppender();
        LogAppender fiLogAppender = new FileAppende("log.txt");

        LogHandler loggerChain = getChainOfLogger(consoleAppender);
        loggerChain.logMessage(Loglevel.DEBUG, "this is debug");
        loggerChain.logMessage(Loglevel.INFO, "this is Info");
        loggerChain.logMessage(Loglevel.ERROR, "this is Error");
    }
}
